### ISSUE TITLE
Still getting stale file handle issues: see #100

### ISSUE THREAD

**Issue by rminnich** [willscott/go-nfs#104]

**Comment by rminnich** [comment]
Also getting it with darwin client, linux host, though less frequently
ls: boot/initrd.img: Stale NFS file handle

**Comment by DUOLabs333** [comment]
Could you check whether https://github.com/DUOLabs333/go-nfs/tree/patch-2 fix your problems?

**Comment by rminnich** [comment]
I think we're good now, I'm not seeing them.
