### ISSUE TITLE
`onRename` errors out with "comparing uncomparable type"

### ISSUE THREAD

**Issue by DUOLabs333** [willscott/go-nfs#105]
This is because I use string slices, which are not comparable.

**Comment by DUOLabs333** [comment]
As an alternative, we can add our own method `IsEqual` for different implementations to implement on their own.

**Comment by DUOLabs333** [comment]
I implemented a hacky workaround (which simply checks if an equal method exists, and if so, calls that) --- should I open a PR?

**Comment by willscott** [comment]
Sure -  that may be fine, and will at least be useful!

**Comment by DUOLabs333** [comment]
Done --- in #106.
