### ISSUE TITLE
A git clone will lead to the server displaying files with corrupted permissions

### ISSUE THREAD

**Issue by DUOLabs333** [willscott/go-nfs#115]
While the underlying file is safe, the view the server presents has the permissions with a lot of question marks.

**Comment by DUOLabs333** [comment]
I've also noticed in this case, it seems that the server uses a cache of the items (ie, only does `Getattr`, not `Readdir`).

**Comment by DUOLabs333** [comment]
I fixed this by using `lookupcache=none`.

**Comment by DUOLabs333** [comment]
However, this is not an ideal solutions as it makes things much slower, and operations on files that do exist don't work.

**Comment by DUOLabs333** [comment]
I think I found the issue --- in nfs.link, the last path component doesn't seem to be decoded properly (so it's something like `[foo ?R???Gc???{u??]`), so Link always fails, which seems to mess up the caching (if `bar` is supposed to be linked to `foo`, and isn't, for some reason, getattr(bar) will try to call getattr(foo), which wouldn't exist).

**Comment by DUOLabs333** [comment]
I'm pretty sure this is due to some wrong casting of the input data (it looks like you copied it from the Symlink side, but the format given in the RFC is different).

**Comment by willscott** [comment]
It sounds like you've narrowed this to an issue in hard links - i find it interesting that a standard git clone ends up doing hard links, but I guess I shouldn't be too surprised

**Comment by DUOLabs333** [comment]
Another possible issue (but one that is much harder to solve) is that the client expects the handles to remain constant after Renames --- however, the Handles only use the path, not the inode, so Renames mess up the cache. One way to fix this is to update the cache with the new path after a successful Rename.

**Comment by DUOLabs333** [comment]
Yeah, I fixed the problem by invalidating the handles of the fromFilename at the end of a successful Rename operation (this also fixes Readdirplus not working). I'll open a PR for that as well.

I originally tried to keep the file handles from going stale by mapping the file handles of the fromFilename to the toFilename. It works, but then I remembered that "A file handle may or may not become stale on a rename." I'll keep the method in , just in case some NFS client is non-compliant and we'll need to switch.

**Comment by DUOLabs333** [comment]
This is added as part of PR #116, as it builds upon each other.
