### ISSUE TITLE
Removing directory leads to `Stale file handle`

### ISSUE THREAD

**Issue by DUOLabs333** [willscott/go-nfs#123]
Create directory, delete it, then do `ls .` --- you will get `Stale file handle`.

**Comment by DUOLabs333** [comment]
The issue is here: `userHandle.InvalidateHandle(fs, obj.Handle)`. This invalidates the parent directory, not the file being deleted. You have to get the handle of the file, if it exists.

**Comment by willscott** [comment]
`onRename` invalidates the specific filename being renamed, so i think there should not be a problem there?

**Comment by DUOLabs333** [comment]
Yes, you're right --- I missed that.
