### ISSUE TITLE
deal this error,please

### ISSUE THREAD

**Issue by tianxia0079** [willscott/go-nfs#138]
![image](https://github.com/user-attachments/assets/d739ca60-8280-4aa0-8e6d-e6e568c686cf)

**Comment by willscott** [comment]
can you confirm that you're attempting to use this on windows?

**Comment by willscott** [comment]
this should be fixed by https://github.com/willscott/memphis/commit/a148a489d367e9e283ef5faacf5ac36834b6f4e9

if you confirm by building with the latest commit in the memphis library, i'll propagate it up to go-nfs.

**Comment by tianxia0079** [comment]
> this should be fixed by [willscott/memphis@a148a48](https://github.com/willscott/memphis/commit/a148a489d367e9e283ef5faacf5ac36834b6f4e9)
> 
> if you confirm by building with the latest commit in the memphis library, i'll propagate it up to go-nfs.

yes.thanks
