### ISSUE TITLE
Chown errors

### ISSUE THREAD

**Issue by chrisdostert** [willscott/go-nfs#22]
When I use the osnfs example and try to chown a file from the client mount, I get an error it's not supported. 

### expected:
chown works

### actual:

client error:
```
chown root hi.txt
chown: hi.txt: RPC struct is bad
```

server error:
```
No file for lookup of ._hi.txt
2021/03/03 13:26:51 call to 0x1125460 failed: No such file or directory
2021/03/03 13:26:51 request: RPC #3742974177 (nfs.SetAttr)
2021/03/03 13:26:51 call to 0x112edc0 failed: lchown /Users/source/repos/github.com/dummy/hi.txt: operation not permitted
```

**Comment by willscott** [comment]
and you can confirm with a `ls -l /Users/source/repos/github.com/dummy/hi.txt` that hi.txt is owned by the user running osnfs and it should have permission to run chown?

**Comment by chrisdostert** [comment]
Interesting; I'm running this all on OSX and it appears I can't chown something to root so that explains why it's not happy. It would be nice if we could pass the actual error through to the NFS client vs. `RPC struct is bad`; is that even possible? 

This might make sense to open as a separate ticket though or maybe rename this one. LMK your preference/thoughts.
