### ISSUE TITLE
Bug in readdirplus causing all files in a directory to be the same

### ISSUE THREAD

**Issue by ziyan** [willscott/go-nfs#32]
There is a bug on this line: https://github.com/willscott/go-nfs/blob/master/nfs_onreaddirplus.go#L73

```golang
handle := userHandle.ToHandle(fs, append(p, c.Name()))
```
This code is called in a loop, looping over the result from `ReadDir()`. The problem here is the usage of `append()`

`p` is a `[]string` that comes from converting the handle to a previously stored `[]string`.

Each time the loop runs, `append(p, ...)` is called to either:

1. create a new slice with `p` copied
2. simply putting `...` into existing `p` slice because it's big enough, return a slice that points to same memory as `p` but a bigger length

If we happened to run into the second case, what happens is:

1. we create a new handle for a file path, add to handle cache
2. we proceed to create a second handle for a second file path, add to handle cache
3. but the second file path and the first file path points to the same memory, and now you have 2 different file handles (uuid in this implementation) pointing to the same path

When a NFS client list the directory, it gets 2 different handles, but they read the same file.

**Comment by willscott** [comment]
Does it make more sense for the onreaddirplus method to make a fully copy of the slice each time it calls `ToHandle`, or to set the expectation to the user handle that the slice it's been given isn't guaranteed to remain constant after the call to `ToHandle`?

It seems the easy fix is to keep the semantics in onreaddirplus the same, and change helpers/cachinghandler to have it's entry be of `strings.Join(p, "/")` and do the copy there.

**Comment by ziyan** [comment]
That would work, but dealing with slice is still tricky. Also on the `FromHandle` you will need to split back into slice. IMHO, having a `joinPath(parent []string, element ...string) []string` convenience function and replace all the `append(p, ...)` in the code might be best for the sake of avoiding similar bugs.

```golang
func joinPath(parent []string, elements ...string) []string {
	joinedPath := make([]string, 0, len(parent))
	joinedPath = append(joinedPath, parent...)
	joinedPath = append(joinedPath, elements...)
	return joinedPath
}
```
