### ISSUE TITLE
mount error

### ISSUE THREAD

**Issue by twoholes** [willscott/go-nfs#45]
hi:
1  start example osview like this:
    ./osview /public 2045
2  use mount like this:
    mount -t nfs -o port=2045,mountport=2045,nfsvers=3,tcp -o nolock 10.243.88.235:/public/ /share/
3  the output at server console:
------------------------------------------------------------------
2021/09/14 20:11:49 request: RPC #4228535329 (nfs.Null)
2021/09/14 20:11:49 request: RPC #4245312545 (nfs.GetAttr)
2021/09/14 20:11:49 call to 0x5dc6a0 failed: Invalid file handle
------------------------------------------------------------------

How can I do above the problem...
help me~~~  thank you
My English is terrible, please forgive me...

**Comment by twoholes** [comment]
I have  printed the debug  info , the func onGetAttr():
	fs, path, err := userHandle.FromHandle(handle)
	if err != nil {
		return &NFSStatusError{NFSStatusStale, err}     // this error happened
	}

**Comment by twoholes** [comment]
![图片](https://user-images.githubusercontent.com/56353176/133259192-a0f2624e-62bd-4225-986d-16a94581dff9.png)

**Comment by willscott** [comment]
The screenshot is showing the client attempting to talk NFS v4 rather than v3.

You may need something like `-t nfs3` rather than `nfsvers=3` on your platform

**Comment by twoholes** [comment]
> 
> 
> The screenshot is showing the client attempting to talk NFS v4 rather than v3.
> 
> You may need something like `-t nfs3` rather than `nfsvers=3` on your platform
hi,
Thank you for your answer, thank you.
Another question is:
mount use nfsv3, the client mount print like this:
-------------------------------------------------------------------------------
mount.nfs: access denied by server while mounting 10.243.88.235:/public
-------------------------------------------------------------------------------
the dir access is OK, I have set nobody:nobody.

the following is net dump:
![图片](https://user-images.githubusercontent.com/56353176/133356694-9a2e2604-731a-4ee6-b79d-b17abe7e0a55.png)

**Comment by willscott** [comment]
The response in the screenshot you highlight appears to be successful.

The screenshot only shows packets for the 'Mount' protocol, not for the 'NFSv3' protocol.

Is it possible that your client is not properly sending its NFSv3 requests also to the server? If it is trying to use a portmapper service, rather than sending messages to the server directly, it won't locate the port automatically.

**Comment by twoholes** [comment]
> sending

In the same server, I start NFS(default 2049) and rpcbind，then in the client I mount like this:
--------------------------------------------------------------------------------------------------
mount -t nfs -onfsvers=3,tcp,noacl 10.243.88.235:/public /share/
--------------------------------------------------------------------------------------------------
it returns OK.
But when I start nfs server with  osview command, it happens "access denied by server " problem.

tcpdump NFS(2049):
![图片](https://user-images.githubusercontent.com/56353176/133366425-d2ee9855-af78-484c-95ba-d832c9970ac8.png)

I am  perplexed  with the result from osview ..
I do just like the useage:
![图片](https://user-images.githubusercontent.com/56353176/133366674-6029fdb7-e806-4ed8-95f7-959dfb508f53.png)

**Comment by twoholes** [comment]
Hi, willscott :
   I try the deamon(osview) in centos7, it's OK.
   also thank you for helping me.
   maby client mount has some problem in rel6 ..

thank you

**Comment by willscott** [comment]
Perhaps you have a different option you need for the client in that version.
In the latest screenshot, you'll see that the 'NFSACL' protocol is used. That may mean you need a different option other than 'noacl' to disable that part of NFS from that client.
