### ISSUE TITLE
go run failed

### ISSUE THREAD

**Issue by zjmnssy** [willscott/go-nfs#55]
$ go run example/osview/main.go .
# github.com/willscott/go-nfs/helpers
helpers/cachinghandler.go:112:31: binary.BigEndian.AppendUint64 undefined (type binary.bigEndian has no field or method AppendUint64)

$ go version
go version go1.18.1 linux/amd64

**Comment by ikmak** [comment]
@zjmnssy 
you should upgrade Go to 1.19
