### ISSUE TITLE
Run and mount on Windows

### ISSUE THREAD

**Issue by ReallyLiri** [willscott/go-nfs#63]
Anyone had any success mounting this server on a Windows machine? I'm not sure if the problem is me not mounting in the right way, or some capability missing in the server.
I'm hosting the server on the same machine, tried to mount it using Powershell `New-PSDrive` and the more native `mount.exe`, but nothing worked, without meaningful error messages or server logs.

**Comment by willscott** [comment]
closing as in-actionable  / has not received any answer yet
