### ISSUE TITLE
Client side files have no execuble permission

### ISSUE THREAD

**Issue by Ordinary-Capability** [willscott/go-nfs#64]
I use the osnfs example code to setup a nfs server on windows 10. 
On a linux device, i mount the server path. But the bin files in the directory have no execute permission.
**ls -l** shows **-rw-rw-rw-** only.
What should i to fix this?

**Comment by willscott** [comment]
Per https://superuser.com/questions/106181/equivalent-of-chmod-to-change-file-permissions-in-windows :
> There is no equivalent to the "executable" (x) Linux attributes in the DOS/Windows file attributes.

The server is using the standard golang library `os` package to read files, and will not see them as executable within a unix file 'mode' view.

You would modify [this method](https://github.com/scorpionknifes/go-nfs/blob/master/filesystem/write_dirfs.go#L93-L95) to expose different permissions to the client than what you get from the underlying OS
