### ISSUE TITLE
What is the smallest set of billy.FS methods that must be implemented in order to list files in a mount?

### ISSUE THREAD

**Issue by DUOLabs333** [willscott/go-nfs#76]
I'm trying to use this library, but even though I implemented `ReadDir`, `Stat`,`Lstat`, `Open`, and `Openfile`, if I do `ls` in the mount, I see nothing. I do see `ReadDir` being called though.

**Comment by willscott** [comment]
That should be sufficient for a mount that has visible files.

You can look at the `helloworld` example, and the backing implementation of the billy `memfs` https://github.com/go-git/go-billy/blob/master/memfs/memory.go to see a fairly simple usage as a library with a file displayed in the mount.

**Comment by DUOLabs333** [comment]
Is it possible to see all errors of the server that may point to why a particular command fails?

**Comment by DUOLabs333** [comment]
However, while I can list a specific file by doing `ls mount/A.txt`, if I try to get any more information, I get `[ERROR] call to {some address} failed: Invalid file handle`

**Comment by willscott** [comment]
when writing the library, i would use wireshark to watch the connection and see what error messages were returned to the client.

there is standard [logging interface](https://github.com/willscott/go-nfs/blob/master/log.go#L66) used by the library, but some error conditions will return errors to the client without resulting in a meaningful server error log.

**Comment by willscott** [comment]
`Sys` is probed in order to set the uid and gid of files https://github.com/willscott/go-nfs/blob/master/file.go#L115 they will be owned as root if sys does not return a unix-compatible struct.

**Comment by DUOLabs333** [comment]
I got wireshark set up, but then I realized I have no idea how to interpret the payload (this is NFS over TCP, I don't know if Wireshark has something for that).

**Comment by willscott** [comment]
wireshark should normally have automatic payload interpretation for NFS. It may not be doing it by default if the traffic is on a non-standard port. You can force decoding as NFS by right clicking and using 'Decode As...'

if you alternatively capture packets on the relevant port while attempting to open / ls the directory, i'm happy to look at the capture and see if I can understand what's going wrong.

**Comment by DUOLabs333** [comment]
I tried to use "Decode As...." but every time I try to add "NFS" it always reset itself. The tcpdump file is attached below (mounting and listing)
[nfs.dmp](https://github.com/willscott/go-nfs/files/13055207/nfs.dmp)

**Comment by DUOLabs333** [comment]
If I use `osview`, Wireshark does decode it as NFS, so maybe it's they way I set up the server? I copied it straight from the README though.

**Comment by DUOLabs333** [comment]
Got it to work --- for CachingHandler, I needed to use `1024` instead of `1`.

**Comment by willscott** [comment]
great - sorry for the trouble getting that to work.

* I'll open an issue to better log that as a bad configuration
* for future reference, the wireshark 'decode as' protocol to use is 'RPC', which does successfully decode the dump you provided above

**Comment by DUOLabs333** [comment]
I don't see 'RPC' (or ONC-RPC) in the list of available protocols.

**Comment by DUOLabs333** [comment]
Ah, I figured it out --- `RPC` is in the `Current` section. However, even when I set `TCP Port` to 10000, it won't decode it.
