### ISSUE TITLE
Can't open device files

### ISSUE THREAD

**Issue by DUOLabs333** [willscott/go-nfs#79]
I'm trying to write an overlay-fs system using NFS --- while I can list the attributes of device files, trying to read from e.g "/dev/random" gives me "No such device or address".

**Comment by DUOLabs333** [comment]
This might be because the server presents it as device 0:0 instead of 1:8.

**Comment by willscott** [comment]
can you see if https://github.com/willscott/go-nfs/pull/80 passes through the major/minor device numbers as expected?

**Comment by DUOLabs333** [comment]
It seems to work with the branch. Thanks!
