### ISSUE TITLE
fs.Stat is called when fs.Lstat should be called

### ISSUE THREAD

**Issue by DUOLabs333** [willscott/go-nfs#87]
When calling `ls` on a file in a mounted directory, files that are symlinks show up as their underlying files. This is because `ls` corresponds to a Lstat call (which doesn't follow symlinks), while the NFS server calls Stat.

**Comment by willscott** [comment]
* This NFS library calls [fs.ReadDir](https://github.com/willscott/go-nfs/blob/master/nfs_onreaddir.go#L147C22-L147C29)
* The examples in this repo use the billy [osfs](https://github.com/go-git/go-billy/blob/master/osfs/os.go#L83) implementation of a backing filesystem, which will translate that into os.ReadDir
* There are some OS complexities in the core golang implementation, but that does generally translate into an underlying [lstat](https://cs.opensource.google/go/go/+/refs/tags/go1.21.3:src/os/dir_unix.go;l=132) call.

**Comment by DUOLabs333** [comment]
Sorry, I meant when doing something like `ls -alh foo.txt`

**Comment by willscott** [comment]
sure.

* the NFS protocol does not itself have a direct `stat` or `lstat` primitive.
* the call on the client will be most likely translated to an NFS `ReadDirPlus` RPC call.

**Comment by DUOLabs333** [comment]
Oh, so `lstat` and `stat` gets converted to the same call?

**Comment by willscott** [comment]
i believe that's correct
