### ISSUE TITLE
Sockets don't work through mount

### ISSUE THREAD

**Issue by DUOLabs333** [willscott/go-nfs#90]
Create socket with `nc -lkU test.sock`, then mount server on directory and try to connect to it with `mount/test.sock` --- you get `Connection refused`.

This is on the same computer.

**Comment by DUOLabs333** [comment]
It might be due to a device number issue again --- `stat` gives different results.

**Comment by willscott** [comment]
https://superuser.com/questions/1608873/does-a-unix-domain-socket-in-an-nfs-exported-fs-magically-work-across-hosts

I don't think there's a way to communicate the internal kernel state about how the socket is supposed to work through the nfs socket

**Comment by DUOLabs333** [comment]
Interestingly, if I try to start nc using the socket in the mount (so, `nc -lU mount/test.sock` instead of `nc -lU test.sock`), I get `[ERROR] call to 0x11ae70 failed: Operation not supported`.

**Comment by DUOLabs333** [comment]
It's probably because `onMknod` has no support.

**Comment by willscott** [comment]
good catch. it should be reasonable straight forward to add that - i think the trick will be that the underlying billy fs interface also doesn't expose anything around this, so we'll need to add another optional interface for handlers to implement if they want to expose that on their filesystem implementation.

**Comment by DUOLabs333** [comment]
Yes --- we could just copy the `syscall` argument list --- path, mode, device number.

**Comment by willscott** [comment]
Do you have a sense of what the underlying system call should be when `Mknod` for a socket is sent over NFS?

* the [rfc](https://www.ietf.org/rfc/rfc1813.txt) indicates that `Mknod` can take a file type of `NF3SOCK` indicating creation of a socket. When that is requested, the only passed data is the `sattr3       pipe_attributes;` - which does not include a major or minor number.

**Comment by willscott** [comment]
I think i have a sketch of the expected backing behavior - working through it in https://github.com/willscott/go-nfs/tree/feat/mknod and will PR once ready.

The rfc is pretty thin on details on the expected semantics of a created socket in particular, but this may be close enough

**Comment by willscott** [comment]
the branch has a first pass at what seems like plausible for this code, and the `osnfs` example supporting `mknod` operations.

if you can point me to concrete repro steps for things not working ("on ubuntu, make an nfs mount, run these lines, get error") i'll be able to get to fixing potential bugs in here faster

**Comment by DUOLabs333** [comment]
Sorry, didn't see this till now: interestingly, you can't create just "hanging" sockets, but it looks like you figured something out. 

There are two reproducers: one, create a mount exposing a local directory. Run  a listening nc server on the underlying local directory. Try to connect to the corresponding socket in the mount. You should get a "Connection refused". However, this does not seem possible to solve.

Another reproducer. Start a listening nc server on the mount. Then try to connect to the socket on the mount. You should get a Remove call and an "Operation not permitted".

**Comment by willscott** [comment]
Updated the branch linked above. I was able to create a socket and a fifo over the mount locally at least.

can you see if that gives you better behavior?

**Comment by DUOLabs333** [comment]
It does seem to work now --- the second reproducer now leads to the expected behavior (I can connect and send messages back and forth). #91 is still an issue though, so sockets wasn't the issue. Thanks!
