### ISSUE TITLE
"Illegal instruction" when trying to run `su user` in chroot in mount

### ISSUE THREAD

**Issue by DUOLabs333** [willscott/go-nfs#91]
I originally thought this was due to a socket (hence #90), but I tested it with `unionfs-fuse`, which also doesn't work with sockets (presumably for the same reason), and it works fine. Comparing the straces, it seems the problem occurs at a specific `munmap`, which corresponds to `/usr/lib/libresolv.so.2`.

**Comment by willscott** [comment]
can you provide the wireshark capture of the NFS messages that are made when you observe this error?

**Comment by DUOLabs333** [comment]
[nfs.dmp](https://github.com/willscott/go-nfs/files/13266186/nfs.dmp)

**Comment by willscott** [comment]
* I don't see any calls to `mknod` or mutation occuring here.
* My best guess looking at this is that there's an expectation of translation of symlinks by the underlying filesystem that may not be happening.

For instance, I see some symlinks that are bing resolved to
absolute paths in the host, lik `/run/systemd/journal/dev-log`, some that have absolute paths like `/home/system/Repos/overlay-nfs/overlay-nfs`,  and others that are relative, like `../run`

**Comment by DUOLabs333** [comment]
By using `ltrace`, it seems the offending high-level function is `calloc`.

**Comment by willscott** [comment]
the most likely thing I can imagine here is that the `calloc` call triggering an `munmap` (so closing what's presumably a file that's been mapped into memory) triggers either a write or a close of that file. I don't see any errors in the dump on either of those nfs calls. - was it frozen at the point you ended the trace above?

**Comment by DUOLabs333** [comment]
No --- and I don't see an OpenFile call. Once su crashes, the mount stays active.

**Comment by DUOLabs333** [comment]
Nevermind --- red herring. I assumed `ltrace` only prints a function after it returns, so I assumed that the `calloc` and `pam_end` were two separate  calls. As it turns out, the error is within `pam_end` itself --- if I add a printf call before and after the call, only the one before the call is executed.

**Comment by DUOLabs333** [comment]
I was able to reproduce the problem:
```
#include <fcntl.h>
#include <sys/mman.h>
#include <errno.h>
#include <stdio.h>
#include <string.h>
#include <dlfcn.h>
int main(int argc, char** argv){
	void *foo=dlopen("test_mount/usr/lib/security/pam_systemd_home.so",RTLD_NOW);
	printf("%p\n",foo);
	dlclose(foo);
}
```

Interestingly, I can only reproduce the problem with `ltrace a.out`, just `./a.out` didn't lead to any coredump.

**Comment by willscott** [comment]
interesting that `pam_end` triggers an illegal instruction

maybe the next step is to run GCC and step through to figure out what within the `pam_end` call leads to the crash?

**Comment by DUOLabs333** [comment]
I just tried it again, and now everything works as expected. I have no idea what I did to fix it.

**Comment by willscott** [comment]
Is there a bug we can identify as occurring at the NFS layer here, or is it safe to close this issue?

**Comment by DUOLabs333** [comment]
It's not clear --- other NFS servers don't have this issue, but I can't seem to find the issue with this particular implementation.

**Comment by DUOLabs333** [comment]
I noticed that even though both sets of libraries are compiled from the same set of sources, the list of exported dynamic functions (`nm -D`) are not the same.

**Comment by DUOLabs333** [comment]
I think I figured out why my recompiled libs worked --- `libpam` dynamically loads pam_systemd_home.so from the same directory its in. Since I placed the new libs in a different folder, obviously pam_systemd_home isn't there, so nothing happens. This implies the issue is with pam_systemd_home --- without it loading, no fault happens.

**Comment by DUOLabs333** [comment]
`pam_end` calls `dlclose`, which causes the error. However, I can't definitively determine which library causes the crash (though presumably it's systemd), as GDB can only show me the pointers, not the actual values.

**Comment by DUOLabs333** [comment]
Using `sudo -u` instead of `su` leads to a SIGBUS in systemd, but this time when doing some string operation in the module, instead of unloading it. It definitely seems like some memory issue, which is weird, as NFS is just a filesystem.

**Comment by DUOLabs333** [comment]
I'm thinking that it may be due to some race conditions --- is there a way to serialize the server so that any command over the same connection is executed in serial order?

**Comment by willscott** [comment]
It is already written in a fully serialized way: https://github.com/willscott/go-nfs/blob/master/conn.go#L52-L64

**Comment by DUOLabs333** [comment]
If you have an x64 computer, can you run the application and see you get the same error (I want to rule out some hardware issues, as I'm on ARM64)? The command will be `sudo ./overlay-nfs /=RO ~/test_mount`; then, in a separate shell, do `sudo chroot ~/test_mount su $USER bash`.

**Comment by DUOLabs333** [comment]
Another issue --- if I run `overlay-nfs` without `sudo`, the first run gets me a `SIGBUS`, though the next run gets me `SIGILL` (this is with `chroot su system`) --- maybe there's a permission issue going on?

**Comment by DUOLabs333** [comment]
Since `SIGBUS` can be gotten with files being modified, this could be related --- I have the following logs in `journalctl`:
```
NFS: server 127.0.0.1 error: fileid changed
                               fsid 0:87: expected fileid 0x2a52d6, got 0x2a5287
```

**Comment by willscott** [comment]
can you see if you get different behavior when using the code with #102 , which fixes a discrepancy in fileid returned for directories?

**Comment by DUOLabs333** [comment]
No, I get the same problem.

**Comment by DUOLabs333** [comment]
I added print statements to both `ToHandle` and `FromHandle`, and I can see that if you start the chroot process again quickly after it exits, the ids handed out inexplicably map to different files (the first run, it will map to file `A`, but during the second run, it will map to id `B`. This is without restarting the NFS server).

**Comment by DUOLabs333** [comment]
Found the issue: the LRU doesn't keep a copy of the list, but the list itself. Since lists are mutable, this means that whenever `path` changes, the item in the LRU changes as well. Making a copy of the list before inserting into the LRU solves this problem.

**Comment by DUOLabs333** [comment]
This also solves the `Illegal Instruction` problem --- this of course leads to a new problem, but that's a different issue.

**Comment by willscott** [comment]
are you able to prepare a PR with the fixed handle LRU behavior, or should I look into it?

**Comment by DUOLabs333** [comment]
I can make a quick PR.

**Comment by DUOLabs333** [comment]
Done (PR #103).
