### ISSUE TITLE
GETATTR does not set fhandle in returned struct

### ISSUE THREAD

**Issue by rminnich** [willscott/go-nfs#99]
readdirplus correctly sets the fileid, but getattr does not. The result is that on gettattr, linux sees a filehandle of zero, and it all goes downhill from there.

The fix is simple, but it appears I can not create a PR yet. So here it is.
From 60a82cddc7fc8ab58886e67da169958efac210f8 Mon Sep 17 00:00:00 2001
From: "Ronald G. Minnich" <rminnich@gmail.com>
Date: Tue, 12 Dec 2023 03:40:17 +0000
Subject: [PATCH] getattr: set the fileid in the returned attrs

Currently, the attr is not set, as it is in readdirplus.
The result is that, after a readdirplus, Linux
detects the fhandle has changed, and interprets that
as an error.

Further, the next use of this file will use an fhandle of all zeros,
causing the server to complain.

Signed-off-by: Ronald G. Minnich <rminnich@gmail.com>
---
 nfs_ongetattr.go | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/nfs_ongetattr.go b/nfs_ongetattr.go
index bf3d68f..c96cfa9 100644
--- a/nfs_ongetattr.go
+++ b/nfs_ongetattr.go
@@ -3,6 +3,7 @@ package nfs
 import (
 	"bytes"
 	"context"
+	"encoding/binary"
 	"os"

 	"github.com/willscott/go-nfs-client/nfs/xdr"
@@ -27,6 +28,7 @@ func onGetAttr(ctx context.Context, w *response, userHandle Handler) error {
 		return &NFSStatusError{NFSStatusIO, err}
 	}
 	attr := ToFileAttribute(info)
+	attr.Fileid = binary.BigEndian.Uint64(handle[0:8])

 	writer := bytes.NewBuffer([]byte{})
 	if err := xdr.Write(writer, uint32(NFSStatusOk)); err != nil {
--
2.34.1

**Comment by rminnich** [comment]
overall, there are a few other places where fileid is not set, and linux is unhappy:
```
[ 1811.830000] NFS: server 192.168.0.10 error: fileid changed
[ 1811.830000] fsid 0:13: expected fileid 0x0, got 0x165b98be2e784cc9
[ 1811.870000] NFS: server 192.168.0.10 error: fileid changed
[ 1811.870000] fsid 0:13: expected fileid 0x0, got 0x15e019a7babe4e62
[ 1811.900000] NFS: server 192.168.0.10 error: fileid changed
[ 1811.900000] fsid 0:13: expected fileid 0x0, got 0x8a54dff6858049b8
```
one option might be to have ToFileAttribute take the handle as well, to fill in the missing information.

**Comment by willscott** [comment]
in the previous update https://github.com/willscott/go-nfs/pull/97 i intended to switch from using the handle for the fileid to rather using either the underlying fileid when present, or a hash of the full pathname of the file when not. The handle will not be guaranteed to be stable in the same way as the path.

Doing a search, it looks like read-dir still uses the handle for the synthetic fileids for the directory itself. I'll fix that.

I am interested in what's getting us '0x0' file id's - maybe we need to be more aggressive about detecting that when returned from the file system and using path hash if so - the logic right now is that if the stat's `os.FileInfo.Sys()` is a `(*syscall.Stat_t)` - then we read the Ino.

**Comment by willscott** [comment]
This should be consistent now with #102
